Logging:
  LogLevel:
    Default: "Information"
    Microsoft: "Warning"
    Microsoft.Hosting.Lifetime: "Information"
    SS14: "Debug"

Serilog:
  Using: [ "Serilog.Sinks.Console" ]
  MinimumLevel:
    Default: Information
    Override:
      SS14: Information
      Microsoft: "Warning"
      Microsoft.Hosting.Lifetime: "Information"
      Microsoft.AspNetCore: Warning

  WriteTo:
    - Name: Console
      Args:
        OutputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}"

  Enrich: [ "FromLogContext" ]

AllowedHosts: "*"

# API URL your watchdog is accessible from.
# This NEEDS to be reachable by the watchdog.
# If you don't want the watchdog to be public,
# do `http://localhost:5000/` here.
#BaseUrl: https://your.domain.com/watchdog/
BaseUrl: http://localhost:5000/


Servers:
  Instances:
    example:
      # Name of the server
      Name: "Birber Station 14"
      # Token to control the instance remotely
      ApiToken: "explosive_honk_assblast"
      # Port OF THE GAME SERVER.
      # This should match the HTTP status API
      # or watchdog can't contact the server.
      ApiPort: 1212

      # Auto update configuration. This can be
      # omitted to skip auto updates.

      UpdateType: "Git"
      Updates:
        # BaseUrl: The URL of the Git repository to watch.
        # This is distinct from the Watchdog-wide BaseUrl.
        BaseUrl: "https://github.com/hyena-network/birber-14/"
        # Branch: The branch to watch.
        Branch: "master"
        # Hybrid ACZ: When enabled, the game server hosts the client zip rather than the watchdog.
        # As of the introduction of delta updating this is now the better way to handle this.
        HybridACZ: true
